framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    http_method_override: true
    trusted_proxies: ['127.0.0.1', '::1', 'a56a-85-168-236-115.ngrok-free.app'] # Remplace avec ton domaine ngrok
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
